blog/urls.py
from django.urls import path
from . views import CategoryList, BlogList, BlogDetail, TagList

#namespace
app_name = 'blog'

urlpatterns = [
    path('', CategoryList, name='categorylist'),
    path('list/cid/<cate_pk>', BlogList, name='bloglist'),
    path('detail/<blog_pk>', BlogDetail, name='blogdetail'),
    path('taglist/<tags_pk>', TagList, name='taglist'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from mdeditor.fields import MDTextField
from django.urls import reverse
# Create your models here.

class Category(models.Model):
    name = models.CharField('分类', max_length=30)

    def __str__(self):
        return '{}'.format(self.name)
    
    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name

class Tags(models.Model):
    name = models.CharField('标签', max_length=40)

    def __str__(self):
        return '{}'.format(self.name)
    
    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name

class Blog(models.Model):
    author = models.ForeignKey(User, verbose_name='作者', on_delete=models.DO_NOTHING)
    category = models.ForeignKey(Category, verbose_name='分类', on_delete=models.DO_NOTHING)
    tag = models.ManyToManyField(Tags, verbose_name='标签')
    title = models.CharField('标题', max_length=100)
    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    content = MDTextField('内容')
    views = models.PositiveIntegerField('阅读量', default=0)

    def __str__(self):
        return '{}'.format(self.title)
    
    def views_in(self):
        self.views += 1
        self.save(update_fields=['views'])
    
    class Meta:
        verbose_name = '博客文章'
        verbose_name_plural = verbose_name
    
    def get_absolute_url(self):
        return reverse('blog:blogdetail', kwargs={'blog_pk':self.pk})

blog/views.py
from django.shortcuts import render
from . models import Tags, Category, Blog
import markdown
from django.db.models.aggregates import Count
import random
# Create your views here.

#显示分类、标签及其数量
def CategoryList(request):
    get_count = Category.objects.annotate(num_posts=Count('blog'))
    get_tags = Tags.objects.annotate(num_posts=Count('blog')).filter(num_posts__gt=0)
    all_in_one = Blog.objects.all()
    get_new_blog = all_in_one.order_by('-created_time')[:15]
    get_hot_blog = all_in_one.order_by('-views')[:15]

    #随机文章
    def random_blogs(except_id=0):
        random_count = 15
        return Blog.objects.exclude(id=except_id).order_by('?')[:random_count]
    get_rand_blog = random_blogs()
    context = {
        'get_count':get_count,
        'get_tags':get_tags,
        'get_new_blog':get_new_blog,
        'get_hot_blog':get_hot_blog,
        'get_rand_blog':get_rand_blog, 
    }
    return render(request, 'blog/category_list.html', context)


#分类标题列表
def BlogList(request, cate_pk):
    titles = Blog.objects.all().filter(category_id=cate_pk).order_by('-created_time')
    #获取文章分类
    cate = Category.objects.get(id=cate_pk)
    #获取分类下的views并升序
    lessviews = titles.order_by('views')[0:9]
    context = {
        'titles':titles,
        'cate':cate,
        'lessviews':lessviews,
    }
    return render(request, 'blog/blog_list.html', context)

#Blog详情
def BlogDetail(request, blog_pk):
    blog = Blog.objects.get(pk=blog_pk)
    blog.content = markdown.markdown(blog.content.replace("\r\n", '  \n'), extensions=[
                                        'markdown.extensions.extra',
                                        'markdown.extensions.codehilite',
                                        'markdown.extensions.toc',
                                        ], safe_mode=True,enable_attributes=False)
    blog.views_in()
    #获取当前文章的所有标签
    tags = blog.tag.all()
    context = {
        'blog':blog,
        'tags':tags,
    }
    return render(request, 'blog/blog_detail.html' ,context)

#标签列表
def TagList(request, tags_pk):
    tags_list = Tags.objects.get(pk=tags_pk)
    blog_name = tags_list.blog_set.all()
    get_tags = Tags.objects.annotate(num_posts=Count('blog')).filter(num_posts__gt=0)
    context = {
        'tags_list':tags_list,
        'blog_name':blog_name,
        'get_tags':get_tags,
    }
    return render(request, 'blog/tags_list.html', context)

templates/blog/blog_detail.html
{% extends "base.html" %}
{% block content %}
<style>
    .label a {
        display: inline;
        padding: .3em 1em .3em;
        font-size: 1em;
        font-weight: bold;
        line-height: 2;
        color: #017E66;
        text-align: center;
        white-space: nowrap;
        vertical-align: baseline;
        border-radius: .25em;
        margin-right: -1.3em;
        background-color: rgba(1,126,102,0.08);
       
    }
    
    .label a:hover {
        color: #fff;
        background-color: #017E66;
    } 
</style>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3><b>{{ blog.title }}</b></h3>
            <span class="glyphicon glyphicon-time">{{ blog.created_time |date:"Y/m/d" }}</span>
            <span class="glyphicon glyphicon-eye-open" style="padding-left:20px">{{ blog.views }}</span>
            {% for tag in blog.tag.all %}
            <span class="label"><a href="{% url 'blog:taglist' tag.pk %}">{{ tag.name }}</a></span>
            {% endfor %}
            <hr>
            {{ blog.content | safe }}
        </div>
    </div>
</div>
{% endblock content %}

templates/blog/blog_list.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h3><b>分类:{{ cate.name }}的文章</b></h3>
            <hr>
            <ul class="ul list-unstyled">
                {% for title in titles %}
                <li><a href="{% url 'blog:blogdetail' title.pk %}">{{ forloop.counter }}.{{ title.title }} </a><span style="color:grey">({{ title.created_time }})</span></li>
                {% empty %}
                该分类未发布文章
                {% endfor %}
            </ul>
        </div>
        <div class="col-md-4">
            <h4>本分类阅读最少的文章</h4>
            <hr>
            {% for less in lessviews %}
            <li class="list-unstyled"><a href="{% url 'blog:blogdetail' less.pk %}">{{ less.title }}</a><span style="color:grey">({{less.views}})</span></li>
            {% empty %}
            该分类未发布文章
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

templates/blog/category_list.html
{% extends "base.html" %}
{% block content %}
<style>
    .mywell {
        font-size: 2rem;
        min-height: 20px;
        color: #bd2d30;
        padding: 19px;
        margin-bottom: 20px;
        background-color:#CED0EA;
    }

    .label a {
        display: inline;
        padding: .3em 1em .3em;
        font-size: 1em;
        font-weight: bold;
        line-height: 2;
        color: #017E66;
        text-align: center;
        white-space: nowrap;
        vertical-align: baseline;
        border-radius: .25em;
        margin-right: -1.3em;
        background-color: rgba(1,126,102,0.08);
        
    }
    
    .label a:hover {
        color: #fff;
        background-color: #017E66;
    }
</style>
<div class="container">
    <div class="row text-center">
        <h3><span class="glyphicon glyphicon-th"></span>全部分类</h3>
        <hr>
        {% for count in get_count %}
        <div class="col-md-3">
            <div class="mywell">
              <span><a href="{% url 'blog:bloglist' count.pk%}">{{ count.name }}</a></span>
              <span class="badge">{{ count.num_posts }}</span>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="row text-center">
        <h3><span class="glyphicon glyphicon-book"></span>标签大全</h3>
        <hr>
        {% for tags in get_tags %}    
        <span class="label"><a href="{% url 'blog:taglist' tags.pk %}">{{ tags.name }}({{ tags.num_posts }})</a></span>
        {% empty %}
        暂无标签
        {% endfor %}
    </div>
    <div class="row" style="margin-top: 50px">
        <div class="col-md-4">
            <h4>最新笔记</h4>
            <hr>
            {% for new in get_new_blog %}
            <li class="list-unstyled"><a href="{{ new.get_absolute_url}}">{{ forloop.counter }}.{{ new.title }}</a>{{ new.created_time|date:"Y-m-d" }}</li>
            {% empty%}
            暂无文章  
            {% endfor %}
        </div>
        <div class="col-md-4">
            <h4>阅读最多笔记</h4>
            <hr>
            {% for hot in get_hot_blog %}
            <li class="list-unstyled"><a href="{{ hot.get_absolute_url }}">{{ forloop.counter }}.{{ hot.title }}</a>阅读({{ hot.views }})</li>
            {% empty %}
            暂无文章  
            {% endfor %}
        </div>
        <div class="col-md-4">
            <h4>随机推荐</h4>
            <hr>
            {% for rand in get_rand_blog %}
            <li class="list-unstyled"><a href="{{ rand.get_absolute_url }}">{{ forloop.counter }}.{{ rand.title }}</a></li>
            {% empty %}
            暂无文章  
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

templates/blog/tags_list.html
{% extends "base.html" %}
{% block content %}
<style>
    .label a {
        display: inline;
        padding: .3em 1em .3em;
        font-size: 1em;
        font-weight: bold;
        line-height: 2;
        color: #017E66;
        text-align: center;
        white-space: nowrap;
        vertical-align: baseline;
        border-radius: .25em;
        margin-right: -1.3em;
        background-color: rgba(1,126,102,0.08);
        
    }
    
    .label a:hover {
        color: #fff;
        background-color: #017E66;
    } 
</style>
<div class="container">
    <div class="row">
        <div class="col-md-10">
            <h3>标签：{{ tags_list.name }}的文章</h3>
            {% for name in blog_name %}
            <li class="list-unstyled"><a href="{% url 'blog:blogdetail' name.pk %}">{{ forloop.counter }}.{{ name.title }}</a><span style="color:grey">({{ name.created_time }})</span></li>
            {% endfor %}
        </div>
        <div class="col-md-2">
            <h4>标签云</h4>
            {% for tags in get_tags %}
            <span class="label"><a href="{% url 'blog:taglist' tags.pk %}">{{ tags.name }}({{ tags.num_posts }})</a></span>
            {% empty %}
            暂无标签  
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}