blog/urls.py
from django.urls import path
from . views import CategoryList, BlogList, BlogDetail, TagList

#namespace
app_name = 'blog'

urlpatterns = [
    path('', CategoryList, name='categorylist'),
    path('list/cid/<cate_pk>', BlogList, name='bloglist'),
    path('detail/<blog_pk>', BlogDetail, name='blogdetail'),
    path('taglist/<tags_pk>', TagList, name='taglist'),
]

note/urls.py
from django.urls import path
from . views import NoteList, NoteDetail

#namespace
app_name='note'

urlpatterns = [
    path('', NoteList, name='notelist'),
    path('detail/<int:note_pk>', NoteDetail, name='notedetail'),

]

selfsource/urls.py
from django.urls import path
from . views import SourcePage

app_name = 'selfsource'
urlpatterns = [
    path('', SourcePage, name='source'),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/code.css'%}">    
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <script src="{% static 'js/jquery.min.js'%}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<style>

</style>
<body>
    {% include "header.html" %}
    <div style="margin-top:80px">
    {% block content %}
    {% endblock content %}
    </div>
    {% include "footer.html" %}
</body>
</html>

templates/footer.html
<style>
    .footer{
        margin-top: 150px;
        background: #0C3C26;
        width: 100%;
        height: 110px;
        /* position: absolute; */
	
    }
    .fixed-footer{
        position: fixed;
        bottom: 0;
        margin-top: 150px;
        background: #0C3C26;
        width: 100%;
        height: 110px;
        position: absolute;
	
    }
    .footer-container{
        margin-top: 10px;
        color: #ffff;
    }
</style>
<script>
$(function(){ 
    function footerPosition(){ $("footer").removeClass("fixed-footer"); 
    var contentHeight = document.body.scrollHeight,//网页正文全文高度 
        winHeight = window.innerHeight;//可视窗口高度，不包括浏览器顶部工具栏 
    if(!(contentHeight > winHeight)){ 
        //当网页正文高度小于可视窗口高度时，为footer添加类fixed-footer 
        $("footer").addClass("fixed-footer"); 
        $(".content").height(winHeight); 
    } else { 
        $("footer").removeClass("fixed-footer"); 
        } 
    } 
    footerPosition();
    $(window).resize(footerPosition); 
});
</script>
<footer class="footer">
        <div class="text-center footer-container">
            <b>锅大虾的自学笔记</b>
	    <p>mooremok@163.com</p>
            <p>粤ICP备19044839号</p>
        </div>
</footer>

templates/header.html
<style>
    .navbar-default .navbar-nav > li > a{
        color: #ffff;
        font-weight: bolder;
    }
    .navbar-default .navbar-nav > li > a:hover {
        color: #44B78B;
    }
    .navbar-default .navbar-nav > .active > a,
    .navbar-default .navbar-nav > .active > a:hover {
        color: #44B78B;
        background-color: #ffffff;
    }
</style>

<nav class="navbar navbar-default navbar-fixed-top" style="background-color:#0C3C26;">
    <div class="navbar-header">
        <DIV class="navbar-brand" style="font-size:32px">
            <a href="{% url 'index' %}"><b><span style="color:#ffff;">缩进世界</span><span style="color:#44B78B; font-size: 20px">TabWorld.cn</span></b></a>
        </DIV>
    </div>
    <div>
        <ul class="nav navbar-nav" style="margin-left:120px">
            <li {% if request.path == '/'%} class ="active" {% endif %}><a href="{% url 'index' %}">首页</a></li>
            <li {% if request.path == '/note/' %} class ="active" {% endif %}><a href="{% url 'note:notelist' %}">错误大全</a></li>
            <li {% if request.path == '/blog/'%} class ="active" {% endif %}><a href="{% url 'blog:categorylist' %}">笔记大全</a></li>
            <li {% if request.path == '/selfsource/'%} class ="active" {% endif %}><a href="{% url 'selfsource:source' %}">自学资源</a></li>
            <!-- <li class="dropdown" style="top:-10px; ">
                <a href="" class="dropdown-toggle" data-toggle="dropdown" style="color:#505050">
                    <b>笔记大全</b>
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu" style="font-size:18px; color:#505050; ">
                    <li><a href="">django</a></li>
                    <li><a href="">python</a></li>
                    <li><a href="">ubuntu</a></li>
                    <li><a href="">mysql</a></li>
                    <li><a href="">git</a></li>
                </ul>
            </li> -->            
        </ul>
    </div>
</nav>

templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12" style="color:#505050">
            <div>
                <h4><b>日志</b></h4>
                <div class="alert alert-success">
                    {% for p in purpose %}                    
                    <p>{{ p.purpose }}</p>
                    {% endfor %}
                </div>
            </div>
            <div>
                <h4><b>出错记录</b></h4>
                <div class="alert alert-danger">                    
                    <p>共搜集错误<b>{{ error_count }}</b>条</p>
                    <span>已解决<b>{{ status_done_count }}</b>条</span>
                    <span>未解决<b>{{ status_not_count }}</b>条</span>
                </div>
            </div>
            <div>
                <h4><b>笔记总数</b></h4>
                <div class="alert alert-info">
                    
                    <p>笔记总数{{ blog_count }}条</p>
                    {% for cate in  category_count %}
                    <p>{{ cate.name }}({{ cate.num_posts }})</p>
                    {% endfor %}
                </div>
            </div>
            <div>
                <h4><b>共收录资源</b></h4>
                <div class="alert alert-warning">                    
                    <p>书籍{{ book_count }}本</p>
                    <p>技术博客{{ tecblog_count }}个</p>
                </div>                
            </div>            
        </div>
    </div>
</div>
{% endblock content %}